#!/usr/bin/env bash

sudo rm /etc/tmpfiles.d/mglru.conf
sudo rm /etc/security/limits.d/memlock.conf
sudo rm /etc/udev/rules.d/64-ioschedulers.rules
sudo sed -i -e 's/,noatime//' /etc/fstab
sudo sed -i -e 's/usbhid.jspoll=1 //' /etc/default/grub
sudo grub-mkconfig -o /boot/efi/EFI/steamos/grub.cfg

#NEW TWEAK DISABLE

systemctl unmask systemd-coredump.socket
systemctl unmask kdumpst-init.service
systemctl unmask steamos-kdumst-layer.service
systemctl unmask steamos-dump-info.service
systemctl unmask steamos-cfs-debugfs-tunings.service
systemctl unmask gpu-trace.service
systemctl unmask steamos-log-submitter.service
systemctl unmask steamos-devkit-service.service
systemctl unmask systemd-journald.service
systemctl unmask systemd-journald-dev-log.socket
systemctl unmask systemd-journald.socket
systemctl unmask systemd-journal-flush.service
systemctl unmask systemd-journald-audit.socket

systemctl start systemd-coredump.socket
systemctl start kdumpst-init.service
systemctl start steamos-kdumst-layer.service
systemctl start steamos-dump-info.service
systemctl start steamos-cfs-debugfs-tunings.service
systemctl start gpu-trace.service
systemctl start steamos-log-submitter.service
systemctl start steamos-devkit-service.service
systemctl start systemd-journald.service
systemctl start systemd-journald-dev-log.socket
systemctl start systemd-journald.socket
systemctl start systemd-journal-flush.service
systemctl start systemd-journald-audit.socket

steamos-readonly disable
rm -f /etc/sysctl.d/99-steamos-tweaks.conf
