#!/usr/bin/env bash

sudo rm /etc/tmpfiles.d/mglru.conf
sudo rm /etc/security/limits.d/memlock.conf
sudo rm /etc/udev/rules.d/64-ioschedulers.rules
sudo sed -i -e 's/,noatime//' /etc/fstab
sudo sed -i -e 's/usbhid.jspoll=1 //' /etc/default/grub
sudo grub-mkconfig -o /boot/efi/EFI/steamos/grub.cfg

#NEW TWEAK DISABLE

sudo systemctl unmask systemd-coredump.socket
sudo systemctl unmask kdumpst-init.service
sudo systemctl unmask steamos-kdumst-layer.service
sudo systemctl unmask steamos-dump-info.service
sudo systemctl unmask steamos-cfs-debugfs-tunings.service
sudo systemctl unmask gpu-trace.service
sudo systemctl unmask steamos-log-submitter.service
sudo systemctl unmask steamos-devkit-service.service
sudo systemctl unmask systemd-journald.service
sudo systemctl unmask systemd-journald-dev-log.socket
sudo systemctl unmask systemd-journald.socket
sudo systemctl unmask systemd-journal-flush.service
sudo systemctl unmask systemd-journald-audit.socket

sudo systemctl start systemd-coredump.socket
sudo systemctl start kdumpst-init.service
sudo systemctl start steamos-kdumst-layer.service
sudo systemctl start steamos-dump-info.service
sudo systemctl start steamos-cfs-debugfs-tunings.service
sudo systemctl start gpu-trace.service
sudo systemctl start steamos-log-submitter.service
sudo systemctl start steamos-devkit-service.service
sudo systemctl start systemd-journald.service
sudo systemctl start systemd-journald-dev-log.socket
sudo systemctl start systemd-journald.socket
sudo systemctl start systemd-journal-flush.service
sudo systemctl start systemd-journald-audit.socket

steamos-readonly disable
sudo rm -f /etc/sysctl.d/99-steamos-tweaks.conf
