#!/usr/bin/env bash

# Activate MGLRU (Multi-Gen. Least Recently Used)
############################################################################### 

cat << EOF | sudo tee /etc/tmpfiles.d/mglru.conf
w /sys/kernel/mm/lru_gen/enabled - - - - 7
w /sys/kernel/mm/lru_gen/min_ttl_ms - - - - 0
EOF

# Unlocking the memory lock
###############################################################################

cat << EOF | sudo tee /etc/security/limits.d/memlock.conf
* hard memlock 2147484
* soft memlock 2147484
EOF

# Changing the I/O (Input/Output) Scheduler
############################################################################### 

cat << EOF | sudo tee /etc/udev/rules.d/64-ioschedulers.rules
ACTION=="add|change", KERNEL=="nvme[0-9]*", ATTR{queue/scheduler}="kyber"
ACTION=="add|change", KERNEL=="sd[a-z]|mmcblk[0-9]*", ATTR{queue/rotational}=="0", 
ATTR{queue/scheduler}="kyber"
EOF

# Preventing the superfluous book-keeping of File Access Times
###############################################################################

sudo sed -i -e '/home/s/\<defaults\>/&,noatime/' /etc/fstab

# Input controller overclocking
###############################################################################

sudo sed -i 's/\bGRUB_CMDLINE_LINUX_DEFAULT="\b/&usbhid.jspoll=1 /' /etc/default/grub
sudo grub-mkconfig -o /boot/efi/EFI/steamos/grub.cfg

# NEW GENERATION TWEAKS
###############################################################################

systemctl stop systemd-coredump.socket
systemctl stop kdumpst-init.service
systemctl stop steamos-kdumpst-layer.service
systemctl stop steamos-dump-info.service
systemctl stop steamos-cfs-debugfs-tunings.service
systemctl stop gpu-trace.service
systemctl stop steamos-log-submitter.service
systemctl stop steamos-devkit-service.service

sysctl -w debug.kprobes-optimization=0
sysctl -w debug.exception-trace=0
sysctl -w kernel.printk="0 0 0 0"
sysctl -w net.ipv4.tcp_timestamps=0
sysctl -w kernel.nmi_watchdog=0

systemctl mask systemd-coredump.socket
systemctl mask kdumpst-init.service
systemctl mask steamos-kdumpst-layer.service
systemctl mask steamos-dump-info.service
systemctl mask steamos-cfs-debugfs-tunings.service
systemctl mask gpu-trace.service
systemctl mask steamos-log-submitter.service
systemctl mask steamos-devkit-service.service

steamos-readonly disable
printf 'debug.kprobes-optimization=0\ndebug.exception-trace=0\nkernel.printk="0 0 0 0"\nnet.ipv4.tcp_timestamps=0\nkernel.nmi_watchdog=0' >> /etc/sysctl.d/99-steamos-tweaks.conf
